### ISSUE TITLE
gcc compiler ICE

### ISSUE THREAD

**Issue by jpcima** [moddevices/mod-plugin-builder#79]
Hello,
we are facing some trouble on current gcc which is in mod-plugin-builder.
It's frequent that this compiler will crash with ICE, and it's hard sometimes to find a workaround for these problems.

This has happened in multiple occasions.
(recent example https://travis-ci.com/github/sfztools/sfizz/jobs/365846891)

Also would it be fine to attempt my own docker image with updated gcc, as device compatibility is concerned?

**Comment by falkTX** [comment]
At some point we will have to update the compiler I guess, that is fair... gcc4 is getting really old now.
So updating the compiler is okay sure, you can see the dwarf branch on how it was done for it, the same could be done for Duo and Duo X eventually.
It makes things more complicated on our side though, as backwards compatibility is very important, and the newer gcc needs newer versions of math libs. So new binaries might not load on current systems (not sure, needs testing).

One thing is for sure, plugins that need a new compiler will also be tagged to only be compatible with MOD releases that support them.
So e.g. sfizz with new gcc will need v1.11 of the MOD-OS that could have this new libraries/compiler.

I am only speculating here though.
Because the compiler is external from the system libraries, maybe this is not an issue at all.

**Comment by falkTX** [comment]
Merged to master is now a modduox-static target that uses gcc-7.5, but it is still compatible with current releases.
Same treatment to be done for modduo soon.

**Comment by falkTX** [comment]
modduo-static target is now on master branch, tested to work with chow-centaur plugin.

@jpcima this clears the issue, correct?

**Comment by jpcima** [comment]
I'll have trouble to check it, given I use exclusively the docker hub image, but feel free to close the issue.

**Comment by falkTX** [comment]
It should be possible to use it in docker, passing `platform` variable as `modduo-static` for example.
I didn't try this myself though.

I will close the issue then.
The stuff with docker would be a separate thing.
